services:
  app:
    image: ghcr.io/villheik/slympialaskuri:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - SESSION_SECRET=vaihda-tama-salaisuus
